version: '3'
services:
  thinkphp:
    build: ThinkPHP-rce/
    image: thinkphp-rce
    container_name: "thinkphp-rce"
    ports:
      - "8080:80"
    environment:
      - FLAG=${flag1}
    networks:
      net1:
        ipv4_address: 192.168.22.95
  webmin:
    build: webmin-rce/
    image: webmin-rce
    container_name: "webmin-rce"
    environment:
      - FLAG=${flag2}
    networks:
      net1:
        ipv4_address: 192.168.22.67
      net2:
        ipv4_address: 192.168.33.29
  weblogic:
    build: weblogic-rce/
    image: weblogic-rce
    container_name: "weblogic-rce"
    networks:
      net2:
        ipv4_address: 192.168.33.192

networks:
  net1:
    ipam:
      config:
        - subnet: "192.168.22.0/24"
  net2:
    ipam:
      config:
        - subnet: "192.168.33.0/24"
