version: '3'
services:
  thinkphp:
    build: ThinkPHP-rce/
    image: thinkphp-rce
    container_name: "thinkphp-rce"
    ports:
      - "8080:80"
    environment:
      - FLAG=${flag1}
    networks:
      net1:
        ipv4_address: 10.10.10.24
  webmin:
    build: webmin-rce/
    image: webmin-rce
    container_name: "webmin-rce"
    environment:
      - FLAG=${flag2}
    networks:
      net1:
        ipv4_address: 10.10.10.81
      net2:
        ipv4_address: 172.16.1.11
  weblogic:
    build: weblogic-rce/
    image: weblogic-rce
    container_name: "weblogic-rce"
    networks:
      net2:
        ipv4_address: 172.16.1.16

networks:
  net1:
    ipam:
      config:
        - subnet: "10.10.10.0/24"
  net2:
    ipam:
      config:
        - subnet: "172.16.1.0/24"
